### ISSUE TITLE
Improve code cleanliness/resliency in celery tasks history

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi-slaveloan#19]
c.f. https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26507914 and https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26507848 we shouldn't use **locals() and probably want a try/except

**Comment by djmitche** [comment]
This issue was moved to mozilla/build-relengapi#265
