### ISSUE TITLE
Don't suppress sa.IntegrityError

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi-slaveloan#22]
Not yet completely sold on this (I'm of the mindset of returning a useful-to-user error message not useful-to-server-admins, in this case, especially since it logs anyway, but):

https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26494952
and 
https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26495293

**Comment by djmitche** [comment]
This issue was moved to mozilla/build-relengapi#264
