### ISSUE TITLE
Better Docstrings for REST Endpoints

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi-slaveloan#23]
These endpoints should provide better prose in the inline docs.

c.f. the following PR comments: https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26494507
https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26495175
https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26503742

**Comment by djmitche** [comment]
This issue was moved to mozilla/build-relengapi#263
