### ISSUE TITLE
Encapsulate bmo functions in bugzilla file

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi-slaveloan#25]
(e.g. create_or_update, dep bugs, and reopen bug logic)

c.f. https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26509415
https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26509606

**Comment by djmitche** [comment]
This issue was moved to mozilla/build-relengapi#261
