### ISSUE TITLE
Consider using REST path semantics better

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi-slaveloan#6]
From Issue #4:

> * Regarding REST endpoints, I agree - we should try to use verbs where possible, and also to keep semantic meaning with the path. So I'd prefer GET /loans?inactive=1 to GET /loans/all, and creating a loan (whether for yourself or someone else) should be via POST /loans.

**Comment by Callek** [comment]
e.g. https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26492742

**Comment by djmitche** [comment]
This issue was moved to mozilla/build-relengapi#273
