### ISSUE TITLE
Implement a notification system for production slaveloan when an admin needs to do manual work

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi-slaveloan#60]
Right now there is no notification when an admin is awaiting manual work. There are many potential ways to implement this, SNS, nagios, e-mail, etc.

To determine at same time is if we want to do any early-warning systems like "jwood@m.c requested a loan of t-snow-r4-001" to #buildduty

**Comment by djmitche** [comment]
This issue was moved to mozilla/build-relengapi#247
